### ISSUE TITLE
Gatsby caches pages / does not rebuild frequently enough

### ISSUE THREAD

**Issue by asross** [sunrisemovement/smvmt-microsite#19]
Changes to hubhub go live in JSON within 10 minutes, but don't immediately take effect on the microsites pages afterwards. I'm guessing this might be a bit tricky to change, but it seems critical to fix.

![image (9)](https://user-images.githubusercontent.com/1022564/84649898-507f2b80-aed5-11ea-9413-a32bbcf42ec2.png)

**Comment by asross** [comment]
Ah, looks like the rebuild occurred by now, so I'm guessing it's on its own periodic schedule. That should be ok, just need to know the maximum time delay so we can notify hubs when they should expect to see changes.

**Comment by lukewestby** [comment]
@asross it's currently once per hour at the top of the hour. it can be adjusted to any interval with a maximum resolution of 1 minute
