### ISSUE TITLE
Events section CSS issues occur when there are more than 3 events

### ISSUE THREAD

**Issue by asross** [sunrisemovement/smvmt-microsite#20]
This is for Sunrise DC, which has five upcoming events:
![image (10)](https://user-images.githubusercontent.com/1022564/84649993-75739e80-aed5-11ea-8c2e-acf5c644d156.png)
The events section is not scrollable, either.

Mostly addressed by https://github.com/sunrisemovement/smvmt-microsite/pull/21

**Comment by lukewestby** [comment]
I added another update to this to have it render in successive rows of 2
